project:
  type: website
  output-dir: docs

website:
  title: "Patrick Finley's Blog"
  navbar:
    right:
      - icon: github
        href: https://github.com/npfinley/npfinley.github.io
      - text: "Home"
        file: index.qmd
        
        
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

execute: 
  cache: false
  
listing:
  type: table


