project:
  type: website
  output-dir: docs
  pre-render: prepare-data.py
  post-render: fix-dates.py

website:
  title: "Patrick Finley's Blog"
  navbar:
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

